spring :
  datasource :
    url : jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username : root
    password : lwm19981012
    driverClassName : com.mysql.jdbc.Driver
    platform: mysql
    schema: classpath:/schema.sql
#    initialization-mode: always
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size: 100MB



mybatis :
  config-location : classpath:/mybatis-config.xml

#logging:
#  level:
#    root: ERROR

# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer_"

#arcface_SDK
config:
  freesdk:
    app-id: 2HoK3LoA2P15VjgbfuJWDHmh5rnZ37DsVGEYpF5Et3tU
    sdk-key: DmFS4cqam9LPEmbD4FkJfC5sBC5qh7UcWTpY5VkdXTxf
    thread-pool-size: 5
  passRate: 85
  cacheExpireAfterWrite: 10 #TimeUnit.MINUTES

filepath:
  faceimage: "d://icms//secret//userfaceimg/"
  roomimage: "d://icms//static//roomimage/"
  filehome: "d://icms//static/"
  staticAccessPath: /static/**

